version: "3.9"
services:
  words-microservice:
    image: "words-microservice"
    ports:
      - "8080:8080"
    networks:
      default:
        aliases:
          - "words-microservice"

  wordle-web:
    image: "wordle-web"
    ports:
      - "8081:8081"
    networks:
      default:
        aliases:
          - "wordle-web"

